### ISSUE TITLE
Header content; Final message -  wishes

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#209]
Info: Start date 2019-11-01 16:23
Info: User "John Doe"
.....
Info: ilivalidator-1.11.1-3a0d49f7bb50f812cf89f80d52830ffd69bc1700
Info: ili2c-5.0.2-20190906
Info: iox-ili-1.20.13-0e35e7a59192f24b5deaf800127552d05ea64efb
Info: maxMemory 253440 KB
.....
Info: dataFile <D:\P...
Info: ilidirs <%JAR_DIR;....>
Info: lookup model <TG1...
Info: lookup model <SIA40...
Info: lookup model <SIA405...
.....
Info: ilifile <\\CHFPS33\iltools\user\MODELS23\Units-20120220.ili>
Info: ilifile <\\CHFPS33\iltools\user\MODELS23\Base_LV95.ili>
Info: ilifile <\\CHFPS33\iltools\user\MODELS23\SIA405_Base_LV95.ili>
Info: ilifile <D:\Program Files\ilivalidator\TG12_SIA405_Wasser_2012_LV95.ili>
.....
Info: validate data...
Info: assume unknown external objects
Info: first validation pass...

**Comment by claeis** [comment]
I added user and start date, but not as first line. I keep ´´ilivalidator-´´ as first line, so that it is easy to recognize it as an ilivalidator log.

I didn't add section headers or separators/empty lines. I want to keep the log file as simple as possible. If you need a different formated output, use the --xtflog and a xslt script or import the xtflog into excel or a db for post processing.
