### ISSUE TITLE
Question: next release of current version?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [claeis/ilivalidator#329]
The "official" version is 1.11.7 and 14 months old, the current "unofficial"(?) version is 1.11.13.
When will there be a new official release?

**Comment by edigonzales** [comment]
I think there are no "offical" and "unoffical" releases. Binary releases are only published on http://downloads.interlis.ch at the moment. And for ili2pg http://www.eisenhutinformatik.ch/interlis/ili2pg/ shows 4.4.2 but 4.6.1 is available. On Github there are no ili2db binary releases but only tags https://github.com/claeis/ili2db/tags

Since it's an open source project it would be nice if someone shows up with some spare time and/or money to make a nice website.

Ah and if someone wants the "unoffical" releases, I would point to the snapshots, that are build on every commit (https://jars.interlis.ch).

**Comment by ltzur** [comment]
Es gibt eine schöne Webseite für alle "offiziellen", sprich geleasten INTERLIS-Werkzeuge: https://www.interlis.ch. Unter https://www.interlis.ch/downloads gibt es eine tabellarische Übersicht über die aktuellsten Versionen, linkerhand kann dann zu jedem einzelnen Werkzeug navigiert werden.
Wenn Claude Eisenhut eine neue Version veröffentlicht, wird das hier automatisiert nachgeführt.

**Comment by edigonzales** [comment]
Cool. Kannte ich so nicht. Also das automatiserte Nachführen.

**Comment by claeis** [comment]
for planned new releases, see https://github.com/claeis/ilivalidator/milestones

**Comment by Pierre-de-la-Verre** [comment]
Thema "Kochbücher" gehört zwar nicht direkt zur Frage, aber wie schaut es damit aus? Sollte das nicht fertig sein?

**Comment by Pierre-de-la-Verre** [comment]
Also liegen auf interlis.ch die aktuellsten Daten. Ich dachte, hier auf Github - rechts unter "Releases - Latest"

**Comment by Pierre-de-la-Verre** [comment]
Danke.
