### ISSUE TITLE
error: not enough disk space

### ISSUE THREAD

**Issue by frantsch** [claeis/ilivalidator#69]
Using ilivalidator 1.2.1 on a 235 MB heavy INTERLIS 2 file (data model _Nutzungsplanung_V1_1_) I keep optaining:

> Error: java.io.IOException: Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung
> Error:   Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung
> Info: ...validation failed

(meaning: not enough disk space).

I have 256 GB free disk space on the drive I am runing ilivalidator on, reading the xtf-file from and saving the results to.

I tried several options of heap memory settings such as _-Xms512m -Xmx2560m_, however it does not seem to have anything to do at all with heap memory. 

Download data and log files (zip) from: `ftp://ohwagaev:ufahnoe1@ftp1.tg.ch`

**Comment by edigonzales** [comment]
I think it is all about the space of the tmp dir since it seems that it caches a lot of data to disk during AREA validation:

`-rw-r--r--   1 stefan  staff    12G 12 Jun 19:57 ioxtmp475385172561176356`

12 GB and it is still running.

You can override the tmp dir with something like `java -Djava.io.tmpdir=/path/to/huge/volume -jar ilivalidator.jar fubar.xtf`

**Comment by edigonzales** [comment]
I was able to validate the file. It ate approx 22 GB of space and took approx 30 minutes to complete on a modern notebook. All temporary data was deleted after finishing the validation.

Btw: no errors found.

**Comment by frantsch** [comment]
Thank you, that solved my problem. I inserted -Djava.io.tmpdir=D:/Temp/ilivalidator and the validation ran through without further Error.
